name: TokenDrip
on:
  schedule:
    - cron: "17 * * * *"  # Run at 17 minutes past every hour
  workflow_dispatch:      # Allow manual triggering
    inputs:
      test_mode:
        description: "Set to 1 for 1k-token test quotas"
        required: false
        default: "0"

jobs:
  quota:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run TokenDrip
        run: python3 runner.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOKENDRIP_TEST: ${{ github.event.inputs.test_mode || '0' }}
          
      - name: Upload state artifacts
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state
          
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: output 